# Generated by Django 2.2 on 2020-03-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200326_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='book',
            name='digital_publisher',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='item_copyright',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='item_format',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_publisher',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='resource_url',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='book',
            name='uid',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
