# Generated by Django 2.2 on 2020-03-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200330_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
